name: Run jest tests
"on": pull_request_target

jobs:
  run_jest_tests:
    permissions: write-all
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest

    # checkout current PR code
    steps:
      - name: Checking out PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Install dependencies
        run: yarn install

      - name:
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # this is just an example, this could be any command that will trigger jest
          test-command: "yarn test"
